name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm run  build
      - name: Lint
        run: npm run lint
  test-browser:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - run: npm install
      - name: Unit tests
        run: npm run test
